
' 
' class diagram styles
'
'-- choose local or repo; commenting out one or the other
!includeurl https://raw.githubusercontent.com/larryr/UsePlantUML/master/dist/Common.puml
'include ../dist/Common.puml

skinparam Class {
    BackgroundColor        BACK1
    BorderColor            BORD1
    ArrowColor             BORD1
    FontColor             #FFFFFF
}
skinparam Arrow {
    Color     BORD1
    FontColor PAPURPLE
    Thickness 2
}
skinparam Note {
    BackgroundColor BACK2
    BorderColor     BORD1
    FontColor       GRAYFONT
}

