' 
' Seqence diagram styles
'
'-- choose local or repo; commenting out one or the other
!includeurl https://raw.githubusercontent.com/larryr/UsePlantUML/master/dist/Common.puml
'include ../dist/Common.puml

skinparam Sequence {
    BoxBackgroundColor          GRAY1
    BoxBorderColor              GRAY2
    DividerFontColor            GRAY3
    DividerBorderColor          GRAY4
    GroupBackgroundColor        GRAY1
    GroupBorderColor            GRAY4
    GroupBorderThickness        1
    GroupFontColor              GRAY4
    GroupHeaderFontColor        GRAY5
    GroupHeaderFontStyle        italic
    LifeLineBackgroundColor     BACK1
    LifeLineBorderColor         BORD1
    ParticipantBackgroundColor  BACK1
    ParticipantBorderColor      BORD1
    ReferenceBorderColor        GRAY4
    ReferenceBorderThickness    1
    ReferenceFontColor          GRAY4
}

skinparam Actor {
    BackgroundColor        BACK1
    BorderColor            BORD1  
}
skinparam Boundary {
    BackgroundColor        BACK1
    BorderColor            BORD1  
}
skinparam Control {
    BackgroundColor        BACK1
    BorderColor            BORD1  
}
skinparam Entity {
    BackgroundColor        BACK1
    BorderColor            BORD1  
}
skinparam Database {
    BackgroundColor        BACK1
    BorderColor            BORD1  
}
skinparam Arrow {
    Color     BORD1
    FontColor PAPURPLE
    Thickness 2
}
skinparam Note {
    BackgroundColor BACK2
    BorderColor     BORD1
    FontColor       GRAYFONT
}
skinparam Collections {
    BackgroundColor BACK1
    BorderColor     BORD1
}
skinparam Queue {
    BackgroundColor BACK1
    BorderColor     BORD1
}

skinparam BoxPadding 10
skinparam ParticipantPadding 5

